#!/bin/bash
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/0.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/0.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/0.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/0.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/0.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/1.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/1.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/1.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/1.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/1.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/2.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/2.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/2.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/2.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/2.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/3.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/3.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/3.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/3.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/3.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/4.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/4.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/4.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/4.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/4.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/5.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/5.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/5.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/5.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/5.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/6.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/6.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/6.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/6.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/6.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/7.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/7.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/7.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/7.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/7.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/8.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/8.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/8.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/8.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/8.output.jck.txt
java -Xmx5G -cp marmot.jar marmot.morph.cmd.Trainer -train-file form-index=1,tag-index=2,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/9.train.jck.txt -tag-morph false -model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/9.model.jck.txt
java -cp marmot.jar marmot.morph.cmd.Annotator --model-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/9.model.jck.txt --test-file form-index=0,/Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/9.test.jck.txt --pred-file /Users/halsaied/PycharmProjects/TextAnnotation/Marmot/Jackkniffing/FR/9.output.jck.txt
